# This file is generated by scripts/generate-py-sdk.py.
# Do not edit by hand.

import json
from typing import Any, Optional
from urllib import error, parse, request

from .types import *

IndexDocumentsHeaders = TypedDict("IndexDocumentsHeaders", {"x-coco-org-id": str, "x-coco-project-id": str})
QueryDocumentsHeaders = TypedDict("QueryDocumentsHeaders", {"x-coco-org-id": str, "x-coco-project-id": str})
IngestBatchHeaders = TypedDict("IngestBatchHeaders", {"x-coco-org-id": str, "x-coco-project-id": str})

class ListConfigsQuery(TypedDict):
    org_id: str
    project_id: NotRequired[Optional[str]]

class CocoClient:
    def __init__(self, base_url: str, api_key: Optional[str] = None) -> None:
        self._base_url = base_url if base_url.endswith('/') else f"{base_url}/"
        self._api_key = api_key

    def _request(
        self,
        method: str,
        path: str,
        headers: Optional[dict[str, str]],
        body: Optional[dict[str, Any]],
        query: Optional[dict[str, Any]],
        expect_json: bool,
    ):
        url = parse.urljoin(self._base_url, path.lstrip('/'))
        if query:
            filtered = {key: value for key, value in query.items() if value is not None}
            if filtered:
                encoded = parse.urlencode(filtered, doseq=True)
                url = f"{url}?{encoded}"
        request_headers: dict[str, str] = {}
        if headers:
            request_headers.update(headers)
        if self._api_key:
            request_headers["authorization"] = f"Bearer {self._api_key}"
        data: Optional[bytes] = None
        if body is not None:
            data = json.dumps(body).encode("utf-8")
            request_headers.setdefault("content-type", "application/json")
        req = request.Request(url, data=data, headers=request_headers, method=method)
        try:
            with request.urlopen(req) as resp:
                payload = resp.read()
        except error.HTTPError as exc:
            payload = exc.read().decode("utf-8", "ignore")
            raise RuntimeError(f"Request failed: {exc.code} {payload}") from exc
        if not expect_json:
            return payload
        if not payload:
            return None
        return json.loads(payload.decode("utf-8"))

    def indexDocuments(self, request: IndexRequest, headers: IndexDocumentsHeaders) -> IndexResponse:
        return self._request("POST", f"/v1/docs/index", headers, request, None, True)

    def queryDocuments(self, request: QueryRequest, headers: QueryDocumentsHeaders) -> QueryResponseEnvelope:
        return self._request("POST", f"/v1/docs/query", headers, request, None, True)

    def ingestBatch(self, request: IngestBatchRequest, headers: IngestBatchHeaders) -> IngestBatchResponse:
        return self._request("POST", f"/v1/ingest/batch", headers, request, None, True)

    def getJob(self, id: str) -> JobStatusResponse:
        return self._request("GET", f"/v1/jobs/{id}", None, None, None, True)

    def jobEvents(self, id: str) -> bytes:
        return self._request("GET", f"/v1/jobs/{id}/events", None, None, None, False)

    def queryMemos(self, request: MemoQueryRequest) -> MemoQueryResponseEnvelope:
        return self._request("POST", f"/v1/memo/query", None, request, None, True)

    def listConfigs(self, query: ListConfigsQuery) -> ListConfigsResponse:
        return self._request("GET", f"/v1/sys/configs", None, None, query, True)

    def upsertConfig(self, request: UpsertConfigRequest) -> IndexingConfigResponse:
        return self._request("POST", f"/v1/sys/configs", None, request, None, True)

    def activateConfig(self, request: ActivateConfigRequest) -> ActivateConfigResponse:
        return self._request("POST", f"/v1/sys/configs/activate", None, request, None, True)

    def health(self) -> HealthResponse:
        return self._request("GET", f"/v1/sys/health", None, None, None, True)

    def pruneProject(self, request: PruneRequest) -> PruneResponse:
        return self._request("POST", f"/v1/sys/prune", None, request, None, True)

    def registerProject(self, request: RegisterProjectRequest) -> RegisterProjectResponse:
        return self._request("POST", f"/v1/sys/register", None, request, None, True)
