/* This file is generated by scripts/generate-ts-sdk.py. */
/* Do not edit by hand. */

export interface ActivateConfigRequest {
  config_id: string;
  org_id: string;
  project_id: string;
}

export interface ActivateConfigResponse {
  active_config_id: string;
}

/** A chunk extracted from a document. */
export interface Chunk {
  /** Chunk content. */
  content: string;
  /** Source document identifier. */
  doc_id: string;
  /** Optional embedding vector. */
  embedding?: number[] | null;
  /** Chunk identifier. */
  id: string;
  /** Optional quality score for the chunk. */
  quality_score?: number | null;
  span: TextSpan;
  /** Whether the chunk has been verified. */
  verified?: boolean | null;
}

/** High-level error categories for CoCo.

Adding new variants is a breaking change for the public API. */
export type CocoErrorKind = "system" | "user" | "network" | "storage" | "compute";

/** Serializable error response used by API layers. */
export interface ErrorResponse {
  kind: CocoErrorKind;
  /** Human-readable error message. */
  message: string;
}

export interface HealthResponse {
  queue: QueueStatusResponse;
  service: string;
  status: string;
  vector_backend: VectorBackendStatus;
  version: string;
  worker: WorkerStatusResponse;
}

/** HNSW index parameters. */
export interface HnswParams {
  /** Construction ef parameter. */
  ef_construction?: number | null;
  /** Number of connections per node. */
  m?: number | null;
}

export interface IndexRequest {
  indexing_config_id?: string | null;
}

export interface IndexResponse {
  status: string;
}

export interface IndexingConfigResponse {
  config: IndexingConfig;
}

export interface IngestBatchRequest {
  activate?: boolean;
  documents: IngestDocument[];
  indexing_config_id?: string | null;
}

export interface IngestBatchResponse {
  job_id: string;
}

export interface IngestChunk {
  chunk_id: string;
  content: string;
  embedding: number[];
  end: number;
  quality_score?: number | null;
  start: number;
  verified?: boolean | null;
}

export interface IngestDocument {
  chunks: IngestChunk[];
  content_hash?: string | null;
  doc_id: string;
  quality_score?: number | null;
  source_ref: string;
  title?: string | null;
  verified?: boolean | null;
}

/** IVF-PQ index parameters. */
export interface IvfPqParams {
  /** Max iterations for IVF training. */
  max_iterations?: number | null;
  /** Number of IVF partitions. */
  num_partitions?: number | null;
  /** Number of PQ sub-vectors. */
  num_sub_vectors?: number | null;
  /** Sample rate for IVF training. */
  sample_rate?: number | null;
}

export interface JobStatusResponse {
  attempts: number;
  created_at: string;
  error?: string | null;
  job_id: string;
  status: string;
  updated_at: string;
  version_id?: string | null;
}

export interface ListConfigsQuery {
  org_id: string;
  project_id?: string | null;
}

export interface ListConfigsResponse {
  active_config_id?: string | null;
  configs: IndexingConfig[];
}

export interface MemoQueryRequest {
  intent: PublicSearchIntent;
  session_token: string;
}

export interface MemoQueryResponseEnvelope {
  data: QueryResponse;
  meta: ResponseMeta;
}

export interface PruneRequest {
  keep?: number | null;
  org_id: string;
  project_id: string;
}

export interface PruneResponse {
  removed: number;
}

/** Filter constraint accepted by the public server API. */
export interface PublicFilter {
  /** Field name to filter on (server allows `doc_id` and `chunk_id`). */
  field: string;
  op: PublicFilterOp;
  /** String-encoded filter value. */
  value: string;
}

/** Filter operator documented for the public server API. */
export type PublicFilterOp = "eq" | "contains";

/** Search intent describing how retrieval should run. */
export interface PublicSearchIntent {
  /** Optional filter list (server allows `doc_id`/`chunk_id` with `eq`/`contains`). */
  filters: PublicFilter[];
  /** Hybrid weight for vector vs. keyword scoring. */
  hybrid_alpha: number;
  /** Optional indexing configuration selection (defaults to the project's default config). */
  indexing_config_id?: string | null;
  /** Optional query embedding (required for `vector` and `hybrid` retrieval). */
  query_embedding?: number[] | null;
  /** Optional user query text (required for `fts` and `hybrid` retrieval). */
  query_text?: string | null;
  reranker?: coco_protocol.RerankerConfig | null;
  retrieval_mode: coco_protocol.RetrievalMode;
  /** Number of candidates to return. */
  top_k: number;
}

export interface QueryRequest {
  indexing_config?: IndexingConfig | null;
  indexing_config_id?: string | null;
  intent: PublicSearchIntent;
  retrieval_config?: RetrievalConfig | null;
}

export interface QueryResponse {
  results: SearchHit[];
}

export interface QueryResponseEnvelope {
  data: QueryResponse;
  meta: ResponseMeta;
}

export interface QueueStatusResponse {
  detail?: string | null;
  mode: string;
  status: string;
}

export interface RegisterProjectRequest {
  name: string;
  org_id: string;
  org_name?: string | null;
  platform?: string | null;
  project_id?: string | null;
  source_ref: string;
}

export interface RegisterProjectResponse {
  active_config_id: string;
  active_version_id?: string | null;
  name: string;
  org_id: string;
  project_id: string;
}

/** Reranker configuration for post-retrieval scoring. */
export interface RerankerConfig {
  /** Model name for reranking. */
  model_name: string;
  /** Number of top candidates to rerank. */
  rerank_top_n: number;
}

/** Response metadata for request-level status. */
export interface ResponseMeta {
  status: ResponseStatus;
}

/** Response freshness indicator. */
export type ResponseStatus = "fresh" | "stale";

/** Retrieval mode for query execution. */
export type RetrievalMode = "vector" | "fts" | "hybrid";

/** A search hit with metadata and chunk payload. */
export interface SearchHit {
  chunk: Chunk;
  meta: SearchHitMeta;
}

/** Metadata associated with a search hit. */
export interface SearchHitMeta {
  /** Optional quality indicator. */
  quality?: number | null;
  /** Similarity or relevance score. */
  score: number;
  /** Whether the result has been verified. */
  verified?: boolean | null;
}

/** A span inside a document, expressed as byte offsets. */
export interface TextSpan {
  /** Exclusive end byte offset. */
  end: number;
  /** Inclusive start byte offset. */
  start: number;
}

export interface UpsertConfigRequest {
  config: IndexingConfig;
  org_id: string;
}

/** Supported vector backend types. */
export type VectorBackendKind = "pg_vector" | "qdrant";

export interface VectorBackendStatus {
  detail?: string | null;
  kind: VectorBackendKind;
  status: string;
  version?: string | null;
}

/** Backend-specific index parameter overrides. */
export interface VectorIndexParams {
  hnsw?: HnswParams | null;
  ivf_pq?: IvfPqParams | null;
}

/** Supported vector similarity metrics. */
export type VectorMetric = "cosine" | "dot" | "l2";

export interface WorkerStatusResponse {
  status: string;
  updated_at?: string | null;
  version: string;
}
